CREATE DATABASE IF NOT EXISTS car_rent_sale_db;
USE car_rent_sale_db;
CREATE TABLE admins (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(100) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE customers (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(100) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE cars (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(150) NOT NULL,brand VARCHAR(100) NOT NULL,model VARCHAR(100) NOT NULL,year VARCHAR(10),color VARCHAR(50),registration_number VARCHAR(50),fuel_type VARCHAR(50),transmission VARCHAR(50),seats INT DEFAULT 4,mileage INT DEFAULT 0,rental_price_per_day DECIMAL(10,2) DEFAULT 0,sale_price DECIMAL(12,2) DEFAULT 0,description TEXT,image VARCHAR(255),status ENUM('available','rented','sold') DEFAULT 'available',condition_label VARCHAR(50) DEFAULT 'Used',car_type ENUM('rental','sale','both') DEFAULT 'both',is_featured TINYINT(1) DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE bookings (id INT AUTO_INCREMENT PRIMARY KEY,car_id INT NOT NULL,customer_name VARCHAR(100) NOT NULL,email VARCHAR(100) NOT NULL,phone VARCHAR(50) NOT NULL,pickup_date DATE NOT NULL,return_date DATE NOT NULL,pickup_location VARCHAR(150),total_days INT NOT NULL,price_per_day DECIMAL(10,2) NOT NULL,total_amount DECIMAL(12,2) NOT NULL,booking_status ENUM('pending','approved','rejected','completed') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (car_id) REFERENCES cars(id) ON DELETE CASCADE);
CREATE TABLE sales_inquiries (id INT AUTO_INCREMENT PRIMARY KEY,car_id INT NOT NULL,customer_name VARCHAR(100) NOT NULL,email VARCHAR(100) NOT NULL,phone VARCHAR(50) NOT NULL,message TEXT,inquiry_status ENUM('new','contacted','closed') DEFAULT 'new',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (car_id) REFERENCES cars(id) ON DELETE CASCADE);
CREATE TABLE contact_messages (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(100) NOT NULL,subject VARCHAR(150),message TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO admins (name,email,password) VALUES ('System Admin','admin@drivehub.com','$2y$12$p.OvcHXzobius8kM/wvPVOY7MjT4ECivOCAKAYUiljfOU1N3PailW');
INSERT INTO cars (title,brand,model,year,color,registration_number,fuel_type,transmission,seats,mileage,rental_price_per_day,sale_price,description,image,status,condition_label,car_type,is_featured) VALUES
('Toyota Land Cruiser V8','Toyota','Land Cruiser','2022','Black','TRK-2022','Diesel','Automatic',7,18000,120.00,68000.00,'Luxury SUV ideal for family trips and executive transport.','https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=1200&auto=format&fit=crop','available','Used','both',1),
('Hyundai Tucson','Hyundai','Tucson','2021','White','TUC-2021','Petrol','Automatic',5,24000,80.00,32000.00,'Reliable SUV with modern comfort and smooth performance.','https://images.unsplash.com/photo-1494905998402-395d579af36f?q=80&w=1200&auto=format&fit=crop','available','Used','rental',1),
('Mercedes-Benz C-Class','Mercedes','C200','2023','Silver','MB-2023','Petrol','Automatic',5,8000,150.00,54000.00,'Elegant sedan suitable for business and personal use.','https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=1200&auto=format&fit=crop','available','Like New','sale',1);
